const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'nugen');

const scenarios = [
{"scenario_id":"SCN-001","title":"VIP Early Arrival + Room 401 AC Failure","context":"Platinum VIP Arjun Mehta arrives 2h early. Room 401 AC compressor failure, ambient 29C. 82% occupancy.","incident":"INC-401-AC | HVAC_COMPRESSOR | CRITICAL | Room 401 | Repair ETA 75 min","affected_departments":["front_desk","maintenance","housekeeping","revenue"],"reasoning_factors":["75-min repair exceeds 10-min VIP tolerance","Room 205 same tier, available, zero revenue displacement","Floor 4 blocked by wedding group","82% limits alternatives"],"expected_severity":"CRITICAL","expected_decision":"Reassign VIP to Room 205. Escort to Club Lounge. Express clean 205. Dispatch tech to 401. Lock 205 from OTA.","expected_actions":[{"dept":"front_desk","action":"Escort Arjun Mehta to Club Lounge with welcome beverage"},{"dept":"housekeeping","action":"15-min express VIP refresh on Room 205"},{"dept":"maintenance","action":"Dispatch HVAC technician Rohan to Room 401"},{"dept":"revenue","action":"Remove Room 205 from OTA, mark Room 401 out-of-order"}],"escalation":"Required — VIP reassignment at 82% occupancy","expected_explanation":"Repair window (75 min) exceeds VIP tolerance. Room 205 optimal — zero revenue impact. Floor 4 unavailable due to wedding block."},
{"scenario_id":"SCN-002","title":"VIP Early Arrival + Room Not Ready","context":"Gold VIP Elena Rostova arrives 90 min early. Suite 501 dirty post-checkout. 2 housekeepers available. 76% occupancy.","incident":"INC-501-DIRTY | HOUSEKEEPING_BACKLOG | HIGH | Suite 501 | Express clean ETA 25 min","affected_departments":["front_desk","housekeeping"],"reasoning_factors":["2 housekeepers enable 25-min tandem clean","Fits Gold VIP tolerance with lounge bridge","76% — no reassignment needed","Poolside voucher as hospitality bridge"],"expected_severity":"HIGH","expected_decision":"Tandem express clean Suite 501. Poolside dining voucher + luggage storage. Do NOT reassign.","expected_actions":[{"dept":"housekeeping","action":"2 attendants — 25-min express tandem clean on Suite 501"},{"dept":"front_desk","action":"INR 2,000 poolside voucher and luggage secure storage"}],"escalation":"Not required","expected_explanation":"Tandem clean resolves in 25 min. Original room can be honored. Reassignment unnecessary."},
{"scenario_id":"SCN-003","title":"Occupied Room Active Plumbing Burst","context":"Standard guest David Kim reports active water leak through Room 304 ceiling. 91% occupancy. Room 308 available and clean.","incident":"INC-304-PIPE | PLUMBING_BURST | CRITICAL | Room 304 | Active structural leak","affected_departments":["maintenance","housekeeping","front_desk"],"reasoning_factors":["Active leak = safety Priority 1","Room 308 available for relocation","91% occupancy — safety supersedes revenue","Wet-vac required to prevent mold"],"expected_severity":"CRITICAL","expected_decision":"Water isolation immediately. Guest relocated to Room 308. Wet-vac deployed. Room 304 in maintenance status.","expected_actions":[{"dept":"maintenance","action":"Isolate Floor 3 water riser within 3 min"},{"dept":"front_desk","action":"Keycards for Room 308, assist luggage transfer"},{"dept":"housekeeping","action":"Wet-vac in Room 304 after shutoff"}],"escalation":"Required — active safety hazard + occupancy >85%","expected_explanation":"Physical safety supersedes revenue at all occupancy levels. Containment within 5 minutes prevents structural damage."},
{"scenario_id":"SCN-004","title":"Occupied Room Electrical Fault — Sparking Outlet","context":"In-house guest reports sparking from Room 206 bathroom outlet. 1 technician on duty. Room 208 available and clean.","incident":"INC-206-ELEC | ELECTRICAL_FAULT | CRITICAL | Room 206 | Sparking outlet","affected_departments":["maintenance","front_desk"],"reasoning_factors":["Sparking outlet = immediate fire safety risk","Technician isolates circuit before any other task","Room 208 available for immediate relocation","No diagnostic splitting during electrical safety task"],"expected_severity":"CRITICAL","expected_decision":"Evacuate Room 206 immediately. Isolate circuit. Relocate guest to Room 208. Full inspection before Room 206 re-enters inventory.","expected_actions":[{"dept":"front_desk","action":"Evacuate guest and escort to Room 208"},{"dept":"maintenance","action":"Isolate Room 206 circuit, inspect wiring fault"}],"escalation":"Required — electrical safety hazard = immediate Manager notification","expected_explanation":"Electrical sparking is a fire risk. Evacuation non-negotiable. Technician completes safety isolation before any other task."},
{"scenario_id":"SCN-005","title":"Housekeeping Shortage — 2 Sick Calls on High Turnover Day","context":"2 of 5 housekeepers sick. 28 checkouts, 22 arrivals, 5 VIP arrivals. 88% occupancy. Only 3 attendants available.","incident":"INC-HK-SICK | STAFFING_DEFICIT | HIGH | MULTIPLE | 40% headcount reduction","affected_departments":["housekeeping","front_desk","revenue"],"reasoning_factors":["3 attendants cannot clean 28 rooms in standard sequence","VIP rooms first by arrival time","Stayovers deferred","Late arrivals (>18:00) identified to extend window"],"expected_severity":"HIGH","expected_decision":"Express Turnover Protocol. VIP rooms first by arrival time. Defer stayovers. Identify late arrivals. Manager authorization required.","expected_actions":[{"dept":"housekeeping","action":"Re-sequence by arrival time — 5 VIP rooms Priority 1"},{"dept":"front_desk","action":"Identify 8+ late arrivals (>18:00), adjust room-ready estimates"},{"dept":"housekeeping","action":"Defer all stayover refreshes to next day"}],"escalation":"Required — express protocol needs Manager sign-off","expected_explanation":"Sequential floor-order cleaning delays all VIP arrivals. Arrival-time sequencing is the only feasible solution."},
{"scenario_id":"SCN-006","title":"Single Technician — Triple Concurrent Room Incidents","context":"Room 204 (TV), Room 302 (safe lockout), Room 405 (toilet blockage) simultaneously at 19:30. 1 evening technician.","incident":"INC-EVENING-BATCH | CONCURRENT_INCIDENTS | HIGH | Rooms 204,302,405","affected_departments":["maintenance","front_desk"],"reasoning_factors":["Sanitation (toilet) = Priority 1 absolute","Safe lockout = guest needs valuables","TV = comfort only, lowest urgency","Single tech: complete each task fully before next"],"expected_severity":"HIGH","expected_decision":"Room 405 (toilet) → Room 302 (safe) → Room 204 (TV). Proactive call to Room 204 with cocktail and ETA.","expected_actions":[{"dept":"maintenance","action":"Room 405 toilet within 10 min. Room 302 safe at 19:45. Room 204 by 20:00."},{"dept":"front_desk","action":"Proactive call to Room 204: complimentary cocktail, 30-min ETA"}],"escalation":"Not required — standard triage within Duty Manager authority","expected_explanation":"Clinical triage: hygiene > security > entertainment. Proactive communication prevents repeat callbacks."},
{"scenario_id":"SCN-007","title":"Outdoor Wedding + Severe Storm Warning","context":"Storm warning: 55 km/h gusts from 17:00. 60-guest outdoor wedding at 18:00. Ballroom Salon A available (capacity 80).","incident":"INC-WEATHER-STORM | WEATHER_EMERGENCY | CRITICAL | Outdoor Lawn | 90-min window","affected_departments":["front_desk","housekeeping","maintenance","revenue"],"reasoning_factors":["90-min window sufficient for orderly indoor move","Ballroom A capacity adequate","Outdoor A/V must be disconnected safely","Event value INR 8.5L — cancellation catastrophic"],"expected_severity":"CRITICAL","expected_decision":"Rain Contingency Plan. Move to Ballroom Salon A in 90 min. Disconnect outdoor A/V. Stage indoor wedding before guests arrive.","expected_actions":[{"dept":"housekeeping","action":"4 staff set tables and flowers in Ballroom A within 60 min"},{"dept":"maintenance","action":"Safely disconnect outdoor A/V and install stage lighting indoors"},{"dept":"front_desk","action":"Ambassadors at entrance with signage directing guests to Salon A"}],"escalation":"Required — major event relocation needs GM sign-off","expected_explanation":"90-min window allows safe orderly transition. Outdoor event in storm conditions is safety and revenue risk."},
{"scenario_id":"SCN-008","title":"Beach Pavilion High Tide Surge Warning","context":"High tide surge warning for beach pavilion area. 12 guests at cabanas. 45-min window. Staff available.","incident":"INC-TIDE-01 | WEATHER_SAFETY | HIGH | Beach Pavilion | 45-min window","affected_departments":["maintenance","front_desk"],"reasoning_factors":["Guest safety from natural event is Priority 1","45-min window allows orderly evacuation","Pool deck is safe alternative","Beach equipment must be secured"],"expected_severity":"HIGH","expected_decision":"Clear beach cabanas. Redirect to pool deck with complimentary beverages. Secure beach furniture.","expected_actions":[{"dept":"front_desk","action":"Politely evacuate 12 guests to pool deck with complimentary beverages"},{"dept":"maintenance","action":"Secure beach furniture and equipment before tide surge"}],"escalation":"Not required — standard safety protocol","expected_explanation":"45-min window sufficient for non-panic evacuation. Guest safety non-negotiable in natural event scenarios."},
{"scenario_id":"SCN-009","title":"High Occupancy + Room Failure — No Equivalent Alternative","context":"Room 101 AC failure at 96% occupancy. Zero Standard Deluxe alternatives. Only suites remain. Outdoor temp 35C.","incident":"INC-NOALT-101 | HVAC_FAILURE | HIGH | Room 101 | Repair ETA unknown","affected_departments":["maintenance","front_desk","revenue"],"reasoning_factors":["96% — no equivalent alternatives","Cross-tier suite upgrade requires Manager authorization","Portable AC as 30-min bridge while diagnosis occurs","Repair ETA unknown — diagnose first"],"expected_severity":"HIGH","expected_decision":"Diagnose + check portable AC. If repair >45 min: Manager-authorized Suite 502 upgrade. Brief guest immediately.","expected_actions":[{"dept":"maintenance","action":"Urgent Room 101 diagnosis AND portable AC unit availability check"},{"dept":"front_desk","action":"Inform guest, offer portable fan bridge, confirm Suite upgrade contingency"},{"dept":"revenue","action":"Pre-authorize Suite 502 if repair ETA >45 min"}],"escalation":"Required — cross-category upgrade at 96% occupancy","expected_explanation":"Zero equivalent inventory forces cross-category upgrade. Pre-authorization prevents at-desk crisis."},
{"scenario_id":"SCN-010","title":"Guest Complaint + Night Staff Shortage","context":"Standard guest in Room 203 reports violent noise from corridor riser at 22:30. 1 night engineer on kitchen freezer alert.","incident":"INC-NOISE-203 | NOISE_COMPLAINT | MEDIUM | Room 203 | Night constraint","affected_departments":["front_desk","maintenance"],"reasoning_factors":["Sole engineer on safety task — cannot split","Room 205 available and quiet","Immediate room move faster than waiting for engineer","Night manager authorizes"],"expected_severity":"MEDIUM","expected_decision":"Immediate room move to quiet Room 205. Engineer inspects riser after kitchen safety task complete.","expected_actions":[{"dept":"front_desk","action":"Offer immediate move to Room 205 with porter assistance"},{"dept":"maintenance","action":"Inspect mechanical riser after kitchen task completion"}],"escalation":"Not required — night room move within Night Manager authority","expected_explanation":"Engineer cannot split from a safety task. Room move resolves guest comfort immediately."},
{"scenario_id":"SCN-011","title":"Late Checkout Blocking Incoming VIP Room","context":"Gold VIP departing Room 305 wants late checkout until 15:00. Diamond VIP arriving at 14:00 for Room 305. Room 307 clean and available.","incident":"INC-LATECO-305 | CHECKOUT_CONFLICT | HIGH | Room 305","affected_departments":["front_desk","housekeeping","revenue"],"reasoning_factors":["Diamond VIP arrival is immovable constraint","Room 307 same category, clean, no conflicts","Departing guest gets lounge + F&B credit as graceful bridge","Revenue confirms Room 307 clear"],"expected_severity":"HIGH","expected_decision":"Decline Room 305 extension. Lounge + INR 1,500 F&B credit for departing guest. Pre-clean Room 307 for Diamond VIP.","expected_actions":[{"dept":"front_desk","action":"Politely decline extension, offer lounge and INR 1,500 F&B credit"},{"dept":"housekeeping","action":"Clean Room 307 — ready by 13:30"},{"dept":"revenue","action":"Confirm Room 307 clear for full Diamond VIP stay, update PMS"}],"escalation":"Not required","expected_explanation":"Diamond VIP arrival non-negotiable. Room 307 resolves both sides. Graceful departure preserves Gold VIP relationship."},
{"scenario_id":"SCN-012","title":"Multiple VIP Arrivals — Housekeeping Bottleneck","context":"3 VIP arrivals between 13:00 and 14:00. 2 Floor 4 rooms still dirty. 1 available housekeeper.","incident":"INC-MULTI-VIP | VIP_CLUSTER | HIGH | Floor 4","affected_departments":["housekeeping","front_desk","revenue"],"reasoning_factors":["1 housekeeper cannot clean 2 rooms simultaneously","Clean by VIP arrival time — earliest first","Lounge escort all 3 VIPs as bridge","Supervisor inspects each room before key release"],"expected_severity":"HIGH","expected_decision":"Lounge escort all 3 VIPs. 1 housekeeper cleans rooms in arrival-time order.","expected_actions":[{"dept":"front_desk","action":"Escort all 3 VIPs to lounge with personalized welcome"},{"dept":"housekeeping","action":"Clean VIP rooms in strict arrival-time order"}],"escalation":"Not required","expected_explanation":"Single-attendant sequencing by arrival time is the only feasible strategy. Lounge removes lobby friction."},
{"scenario_id":"SCN-013","title":"Room Failure — No Alternate, Presidential VIP In-House","context":"Suite 502 plumbing failure. Presidential VIP in-house. 97% occupancy — zero equivalent alternatives. Repair ETA 2 hours.","incident":"INC-502-PLUMB | PLUMBING_FAILURE | CRITICAL | Suite 502 | 2h repair, no alternatives","affected_departments":["maintenance","front_desk","revenue"],"reasoning_factors":["Presidential VIP — GM personal intervention mandatory","97% — no Presidential alternatives","Private dining room as interim VIP hospitality space","INR 30,000 service recovery credit"],"expected_severity":"CRITICAL","expected_decision":"GM personally attends VIP. Private dining as interim space. Full repair in 2 hours. INR 30,000 service recovery.","expected_actions":[{"dept":"front_desk","action":"GM personal visit with INR 30,000 service recovery credit and formal apology"},{"dept":"maintenance","action":"Begin plumbing repair immediately — complete within 2h"}],"escalation":"Required — Presidential VIP + no alternatives + compensation above threshold = GM mandatory","expected_explanation":"When no alternative exists, service recovery replaces relocation. Presidential relationship requires GM personal intervention."},
{"scenario_id":"SCN-014","title":"Housekeeping Backlog — 12 Late Checkouts","context":"12 unexpected late checkouts 11:30-12:00. 10 arrivals from 13:00. Only 4 housekeepers. 3 arrivals flight-delayed to 16:30.","incident":"INC-HK-BACKLOG | HOUSEKEEPING_BACKLOG | HIGH | MULTIPLE | Labor deficit","affected_departments":["housekeeping","front_desk"],"reasoning_factors":["4 attendants cannot clean 12 rooms before 13:00 in full","3 flight-delayed arrivals reduce immediate pressure","Dynamic clean sequence by arrival urgency","Express protocol authorized by supervisor"],"expected_severity":"HIGH","expected_decision":"Clean by arrival urgency. Defer 3 delayed-arrival rooms. Express protocol for 9 priority rooms. Update Front Desk on realistic room-ready times.","expected_actions":[{"dept":"housekeeping","action":"Re-sequence by arrival urgency — 3 delayed-arrival rooms deferred to 15:00"},{"dept":"front_desk","action":"Update room-ready estimates and proactively communicate delays to arriving guests"}],"escalation":"Not required","expected_explanation":"Urgency sequencing optimizes guest experience within the labor constraint."},
{"scenario_id":"SCN-015","title":"WhatsApp Lockout — Family with Child","context":"In-house family guest Meera Nair messaged WhatsApp at 21:45: locked outside Room 208 with 5-year-old. RFID battery depleted.","incident":"INC-WA-KEY | ACCESS_LOCKOUT | HIGH | Room 208 | Depleted RFID battery","affected_departments":["front_desk","maintenance"],"reasoning_factors":["Child in corridor at night — elevated urgency even for Standard guest","WhatsApp acknowledgement within 60 seconds mandatory","Override key resolves in 3 minutes","Battery replacement in morning — don't disturb sleeping child"],"expected_severity":"HIGH","expected_decision":"WhatsApp acknowledgement in 60 sec. Runner with override key to Room 208 within 3 min. Morning battery replacement scheduled.","expected_actions":[{"dept":"front_desk","action":"60-sec WhatsApp reply. Runner dispatched with override key immediately."},{"dept":"maintenance","action":"Schedule RFID battery replacement for 10:00 tomorrow"}],"escalation":"Not required","expected_explanation":"Child in corridor at night is time-critical. Override key is fastest resolution. Morning swap prevents recurrence."},
{"scenario_id":"SCN-016","title":"Telegram Noise Complaint — Late Night","context":"Telegram bot: Villa 101 Silver VIP reports loud music from Villa 102 at 23:15. Post quiet hours (22:00).","incident":"INC-TEL-NOISE | NOISE_COMPLAINT_DIGITAL | MEDIUM | Villa 101","affected_departments":["front_desk"],"reasoning_factors":["Digital channel: 60-sec automated acknowledgement mandatory","Quiet hours policy clear — courteous enforcement","Security + Duty Manager for Villa 102 visit","Follow-up Telegram confirmation after resolution"],"expected_severity":"MEDIUM","expected_decision":"Automated Telegram ack within 60 sec. DM + Security courteous intervention at Villa 102. Follow-up message after resolution.","expected_actions":[{"dept":"front_desk","action":"60-sec Telegram response. DM + Security visit Villa 102 for quiet hours enforcement. Follow-up message to Villa 101."}],"escalation":"Not required","expected_explanation":"Digital ack prevents escalation. Physical enforcement resolves in 10 minutes."},
{"scenario_id":"SCN-017","title":"Revenue Conflict — Room Reassignment Cannibalizes Group Block","context":"Front Desk proposes upgrading Silver VIP to Room 408. Room 408 is part of 20-room corporate block arriving tomorrow. Room 502 (equivalent, unblocked) available. 72% occupancy.","incident":"INC-REVENUE-BLOCK | INVENTORY_CONFLICT | MEDIUM | Room 408","affected_departments":["front_desk","revenue"],"reasoning_factors":["Room 408 in confirmed corporate block","Assigning today creates tomorrow displacement conflict","Room 502 equivalent, no conflicts","72% occupancy provides flexibility"],"expected_severity":"MEDIUM","expected_decision":"Deny Room 408. Assign Room 502 instead. Revenue updates PMS.","expected_actions":[{"dept":"revenue","action":"Reject Room 408 — corporate block integrity maintained. Approve Room 502."},{"dept":"front_desk","action":"Offer Silver VIP upgrade to Room 502"}],"escalation":"Not required","expected_explanation":"Assigning a blocked room displaces a confirmed corporate guest. Room 502 satisfies both needs."},
{"scenario_id":"SCN-018","title":"Multiple Incidents — One Technician","context":"Pool pump offline AND Room 201 Gold VIP AC failure simultaneously at 11:30. 1 technician. Outdoor temp 34C.","incident":"INC-DUAL-FAIL | CONCURRENT_FAILURES | HIGH | Pool + Room 201","affected_departments":["maintenance","front_desk","revenue"],"reasoning_factors":["Pool affects all 67 guests — broader impact","Gold VIP Room 201 singular but high impact","Secondary pool backup pump takes 20 min — resolve pool first","Portable fan bridge for Room 201","On-call tech needed"],"expected_severity":"HIGH","expected_decision":"Technician to pool first — secondary backup pump (20 min). Portable fan + note to Gold VIP Room 201. Authorize on-call tech.","expected_actions":[{"dept":"maintenance","action":"Cycle secondary pool backup pump (20 min). Then Room 201 diagnosis."},{"dept":"front_desk","action":"Portable fan and apology note to Gold VIP in Room 201. 30-min ETA."},{"dept":"maintenance","action":"Authorize emergency on-call tech callback for Room 201 HVAC"}],"escalation":"Required — on-call callback needs Manager authorization","expected_explanation":"Pool failure at 34C affects all guests simultaneously. Sequential triage is correct when constrained to one technician."},
{"scenario_id":"SCN-019","title":"Room Blocked for Maintenance at High Occupancy","context":"Room 406 requires 48h isolation for water damage drying. 94% occupancy. 4 upcoming Deluxe arrivals in next 48h.","incident":"INC-MAINT-BLOCK | MAINTENANCE_ISOLATION | HIGH | Room 406 | 48h out-of-order","affected_departments":["maintenance","revenue"],"reasoning_factors":["Cannot defer — wet walls mold within 24h extending closure to 10+ days","4 upcoming Deluxe arrivals need proactive audit","Revenue must prepare alternatives now","Reactive handling creates check-in crisis"],"expected_severity":"HIGH","expected_decision":"Proceed with Room 406 isolation immediately. Revenue runs 48h Deluxe reservation audit and prepares reassignment plans.","expected_actions":[{"dept":"maintenance","action":"Begin Room 406 drying immediately — do not defer"},{"dept":"revenue","action":"Audit all Deluxe arrivals in next 48h — identify affected guests, prepare upgrade/alternative plans"}],"escalation":"Required — room offline at 94% needs Manager authorization","expected_explanation":"Deferring risks extending closure from 48h to 10+ days. Proactive audit prevents check-in desk crisis."},
{"scenario_id":"SCN-020","title":"VIP Complaint Escalation — Second Report After Failed Intervention","context":"Platinum VIP Rohit Singhania in Room 302 second noise complaint at 02:30. First intervention 23:00 only partially worked. Guest demanding GM. Room 304 quiet garden side, available.","incident":"INC-VIP-NOISE-ESC | PERSISTENT_NOISE | HIGH | Room 302 | Second escalation","affected_departments":["front_desk","maintenance"],"reasoning_factors":["Second complaint after failed intervention — GM mandatory","Guest has explicitly requested GM","Room 304 quiet garden-facing — room move is correct resolution","HVAC duct may be mechanical source"],"expected_severity":"HIGH","expected_decision":"Wake on-call GM. Offer immediate Room 304 move with porter at 02:30. GM personal apology. Maintenance inspects HVAC duct after guest vacates.","expected_actions":[{"dept":"front_desk","action":"Contact on-call GM immediately. Offer Room 304 move with porter."},{"dept":"maintenance","action":"Inspect Floor 3 corridor HVAC duct for vibration after guest vacates"}],"escalation":"Required — Platinum VIP explicitly requested GM; second escalation = mandatory","expected_explanation":"Second failure + GM request = non-negotiable escalation. Room 304 eliminates noise by geography."},
{"scenario_id":"SCN-021","title":"Multiple AC Failures — Shared Circuit Suspected","context":"Rooms 201, 203, 206 HVAC stop cooling simultaneously at 14:30. Outdoor temp 36C. Platinum VIP in Room 203. 84% occupancy.","incident":"INC-HVAC-FLOOR2 | MULTI_HVAC | CRITICAL | Floor 2 | Common circuit suspected","affected_departments":["maintenance","front_desk","housekeeping","revenue"],"reasoning_factors":["3 simultaneous failures on same floor = shared electrical fault","Diagnose Floor 2 circuit breaker first — may resolve all 3 in 15 min","Platinum VIP Room 203 relocated immediately — zero tolerance","Rooms 205 and 207 prepared as contingencies"],"expected_severity":"CRITICAL","expected_decision":"Test Floor 2 circuit breaker first. Relocate Platinum VIP from 203 to 205 immediately. Prepare 205 and 207 as contingencies for 201 and 206.","expected_actions":[{"dept":"maintenance","action":"Test Floor 2 HVAC circuit breaker panel for common fault"},{"dept":"front_desk","action":"Relocate Platinum VIP from Room 203 to 205 immediately with escort"},{"dept":"housekeeping","action":"Prepare Rooms 205 and 207 for potential standard guest relocations"}],"escalation":"Required — multiple failures at 84% occupancy needs Manager coordination","expected_explanation":"Three simultaneous failures = shared root cause. Circuit fix may resolve all 3 in 15 min vs. three 75-min individual repairs."},
{"scenario_id":"SCN-022","title":"Housekeeping-Maintenance Dependency Deadlock","context":"Room 303 cannot be cleaned: maintenance blocking access panel. Maintenance cannot repair: housekeeping storage in the way. Silver VIP arriving 15:00. 2-hour window.","incident":"INC-DEP-DEADLOCK | OPERATIONAL_DEADLOCK | MEDIUM | Room 303","affected_departments":["maintenance","housekeeping","front_desk"],"reasoning_factors":["Classic deadlock — each team blocked by the other","Simultaneous entry breaks deadlock","Housekeeping clears access (5 min), both teams work in parallel","2-hour window is sufficient"],"expected_severity":"MEDIUM","expected_decision":"Simultaneous room entry. Housekeeping clears panel access (5 min). Both teams proceed in parallel. Room ready 30 min before VIP arrival.","expected_actions":[{"dept":"housekeeping","action":"Enter Room 303, clear panel access in 5 min, clean remaining areas concurrently"},{"dept":"maintenance","action":"Enter Room 303 after panel cleared — complete repair in 25 min"}],"escalation":"Not required — resolved through coordination, no additional resources","expected_explanation":"Deadlock broken by concurrent room entry. Sequential waiting is operationally unnecessary."},
{"scenario_id":"SCN-023","title":"Emergency Maintenance — Kitchen Freezer Temperature Spike","context":"Walk-in freezer BMS alert: rising from -18C to -9C in 45 min. Dinner service in 2h for 85 guests. INR 3.5L food inventory at risk.","incident":"INC-KITCHEN-FREEZE | KITCHEN_EMERGENCY | CRITICAL | Kitchen | Compressor fault","affected_departments":["maintenance","front_desk"],"reasoning_factors":["Food safety: frozen food cannot exceed -12C for >2h","2h window before dinner service","Diagnosis + preservation contingency in parallel","Emergency dry-ice as preservation bridge if repair >60 min"],"expected_severity":"CRITICAL","expected_decision":"Immediate freezer diagnosis. Alert F&B Director + GM. Order emergency dry-ice if repair >60 min.","expected_actions":[{"dept":"maintenance","action":"Diagnose freezer compressor fault immediately"},{"dept":"front_desk","action":"Alert F&B Director and GM — dinner menu may need modification"}],"escalation":"Required — food safety + dinner service risk = GM notification mandatory","expected_explanation":"Parallel action: diagnosis + preservation contingency. Waiting for diagnosis alone risks missing food safety window."},
{"scenario_id":"SCN-024","title":"Near-Full Occupancy + Revenue Protection","context":"Room 406 taken offline for 48h. Effective occupancy 96%. 4 confirmed Deluxe arrivals affected in next 48h.","incident":"INC-OOO-406 | MAINTENANCE_ISOLATION | HIGH | Room 406 | 48h window","affected_departments":["maintenance","revenue"],"reasoning_factors":["Isolation cannot be deferred — mold risk","4 Deluxe arrivals in 48h horizon need proactive alternatives","Proactive audit now prevents at-desk confrontation","Upgrade authorization needed"],"expected_severity":"HIGH","expected_decision":"Maintenance proceeds immediately. Revenue audits all 48h Deluxe arrivals and pre-clears alternatives or upgrades. Manager approves upgrades.","expected_actions":[{"dept":"maintenance","action":"Begin Room 406 remediation immediately"},{"dept":"revenue","action":"48h Deluxe reservation audit — pre-clear alternatives or upgrades for each affected arrival"}],"escalation":"Required — near-full occupancy + upgrade authorizations","expected_explanation":"Proactive revenue audit converts potential crisis to smooth check-in. Reactive handling leaves guests with no room and no solution."},
{"scenario_id":"SCN-025","title":"Complex Multi-Department — 3 Simultaneous Crises","context":"10:45 AM: Diamond VIP Arjun Mehta in lobby, Room 401 AC failure (CRITICAL). Pool pump offline (HIGH). Banquet cleanup needed before 12:00 (MEDIUM). 2 technicians, 2 housekeepers, 2 front desk.","incident":"INC-COMPLEX-01 | MULTI_CRISIS | CRITICAL | Room 401 + Pool + Banquet","affected_departments":["front_desk","maintenance","housekeeping","revenue"],"reasoning_factors":["VIP lobby escort is Priority 1 — 0-min tolerance — Front Desk acts NOW","2 technicians: Rohan to Room 401, Vikram to pool — parallel","2 housekeepers: Priya to Room 205 VIP refresh, Maria to banquet after 205 confirmed","Banquet 75-min window — lowest urgency, last","All tracks parallel — no sequential queuing"],"expected_severity":"CRITICAL","expected_decision":"Parallel 5-track response: VIP escort NOW. Rohan to 401. Vikram to pool. Priya to Room 205. Maria to banquet after 205 confirmed.","expected_actions":[{"dept":"front_desk","action":"Escort Diamond VIP to Club Lounge IMMEDIATELY"},{"dept":"maintenance","action":"Rohan to Room 401 diagnosis. Vikram to pool secondary pump."},{"dept":"housekeeping","action":"Priya: express VIP refresh on Room 205. Maria: banquet cleanup after Room 205 confirmed started."},{"dept":"revenue","action":"Lock Room 205 from OTA. Mark Room 401 out-of-order."}],"escalation":"Required — Diamond VIP reassignment + multi-incident = GM must be briefed","expected_explanation":"This is exactly the scenario Resort 360 was built for. No single department sees all 3 crises. Parallel deployment resolves all three. Sequential handling guarantees at least one failure."}
];

const benchmark = [
{"benchmark_id":"BEN-001","title":"Silver VIP Early Arrival — Room Dirty, Lounge Closed","input":{"situation":"Silver VIP arrives 45 min early. Room dirty. Club Lounge closed for cleaning. 3 housekeepers available. 70% occupancy."},"expected_reasoning":"3 attendants enable express clean in 20 min. Lounge unavailable — offer pool deck or lobby beverage as alternative. No reassignment needed.","expected_action":"Express clean by 2 attendants. Pool deck hospitality setup. 20-min realistic promise.","escalation":"No","tests":"VIP protocol without lounge option"},
{"benchmark_id":"BEN-002","title":"Standard Guest AC Failure — Suite Available Only","input":{"situation":"Standard guest Room 301 AC fails. 1 technician. Repair ETA 90 min. No Standard alternatives. Only suites free. 45% occupancy."},"expected_reasoning":"Low occupancy — revenue risk low. Suite upgrade warranted for 90-min uninhabitable room even for Standard guest. Manager authorization required for cross-tier upgrade.","expected_action":"Offer Suite upgrade at same rate. Maintenance repairs Room 301 for future use.","escalation":"Yes — cross-category upgrade requires Manager authorization","tests":"Occupancy threshold effect on upgrade latitude"},
{"benchmark_id":"BEN-003","title":"Two VIP Arrivals — One Room Ready, One Not","input":{"situation":"Platinum and Gold VIPs arriving within 30 min of each other. Platinum room ready. Gold room dirty. 1 housekeeper."},"expected_reasoning":"Platinum room ready — no action needed. Housekeeper dedicated to Gold VIP room. Gold VIP escorted to lounge. Platinum checks in normally.","expected_action":"Housekeeper starts Gold VIP room. Gold VIP lounge escort. Platinum checks in.","escalation":"No","tests":"Multi-VIP triage with adequate resources for one track"},
{"benchmark_id":"BEN-004","title":"3 Low-Priority Maintenance Rooms Same Morning","input":{"situation":"Rooms 104, 207, 310 report minor issues (dripping tap, burnt bulb, TV flicker) at 09:00. 2 technicians. All standard rooms. 80% occupancy."},"expected_reasoning":"None critical. 2 technicians can address sequentially without escalation. Occupied rooms first.","expected_action":"Tech 1: Room 104 (occupied) dripping tap. Tech 2: Room 207 burnt bulb. Room 310 TV in afternoon.","escalation":"No","tests":"Non-urgent triage with adequate staff"},
{"benchmark_id":"BEN-005","title":"Group Arrival 30 Min Early — 3 Rooms Not Ready","input":{"situation":"25-person corporate group arrives 13:30 (30 min early). 3 of 8 rooms dirty. 4 housekeepers. Meeting at 15:00."},"expected_reasoning":"30-min early is minor variance. 4 housekeepers clean 3 rooms in 35 min using tandem pairs. Group in conference area as bridge. Meeting at 15:00 gives adequate buffer.","expected_action":"2 tandem teams clean 3 rooms in parallel (35 min). Group in conference area. All rooms ready by 14:15.","escalation":"No","tests":"Group arrival variance handling"},
{"benchmark_id":"BEN-006","title":"VIP Room Failure vs. Safety System Fault — 1 Technician","input":{"situation":"VIP room AC fails simultaneously with stairwell emergency lighting circuit trip. 1 technician."},"expected_reasoning":"Emergency lighting is a fire safety system — must be prioritized over VIP comfort. Safety system first. VIP gets lounge escort and realistic ETA.","expected_action":"Technician to emergency lighting first. VIP lounge escort with 45-min AC repair ETA.","escalation":"Yes — safety system failure requires immediate Manager notification","tests":"Safety system vs. VIP experience priority conflict"},
{"benchmark_id":"BEN-007","title":"Unauthorized Upgrade Conflicts With Incoming VIP","input":{"situation":"Front Desk upgraded standard guest to suite without Revenue check. Revenue discovers the suite is reserved for an incoming VIP tonight. 85% occupancy."},"expected_reasoning":"Upgrade made without Revenue clearance is a protocol violation. Incoming VIP reservation takes precedence. Standard guest must be politely moved to equivalent Standard room.","expected_action":"Politely move standard guest to available Standard room with F&B credit apology. Restore suite for incoming VIP.","escalation":"Yes — protocol violation + incoming VIP conflict requires Manager notification","tests":"Revenue block enforcement and protocol compliance"},
{"benchmark_id":"BEN-008","title":"Mold Suspected During Checkout Room Turnover","input":{"situation":"Housekeeper discovers dark ceiling stains in Room 405 during turnover. Next arrival in 4 hours."},"expected_reasoning":"Suspected mold is health and safety issue. Room cannot be turned over until maintenance inspects. If confirmed: 3-5 day remediation. Incoming guest proactively reassigned.","expected_action":"Halt Room 405 turnover. Maintenance inspection within 30 min. If confirmed mold: isolation + proactive reassignment.","escalation":"Yes — health and safety discovery escalates based on inspection result","tests":"Health safety discovery protocol during housekeeping"},
{"benchmark_id":"BEN-009","title":"Mid-Stay Room Change — Partial Availability Conflict","input":{"situation":"Gold VIP on 5-night stay requests room change to Room 501 (ocean view). Room 501 free for 3 nights but reserved Night 4. 78% occupancy."},"expected_reasoning":"Moving guest creates forced mid-stay move on Night 4 — unacceptable for Gold VIP. Check if ocean view room available for full remaining stay. If not, offer spa credit.","expected_action":"Check full-stay ocean view availability. If yes: move guest. If no: spa credit and explain constraint.","escalation":"No","tests":"Mid-stay change with partial availability conflict"},
{"benchmark_id":"BEN-010","title":"WhatsApp Complaint — Temperature Issue, Guest Refuses Relocation","input":{"situation":"Standard in-house guest WhatsApp at 14:00: room too hot, AC working but thermostat drift. Repair: recalibration in 20 min. Guest refuses to move."},"expected_reasoning":"Thermostat recalibration is 20-min in-room fix. Guest prefers to stay — no relocation needed. Not a safety issue. Cold drinks as gesture during wait.","expected_action":"Maintenance thermostat recalibration in Room within 20 min. Complimentary cold drinks delivered.","escalation":"No","tests":"In-room repair when guest refuses relocation"},
{"benchmark_id":"BEN-011","title":"Scheduled Fire Drill During Peak Checkout","input":{"situation":"Scheduled fire drill at 11:00 coincides with peak 30-guest checkout rush."},"expected_reasoning":"Drill is a known event — must have been coordinated with Front Desk. Checkout pauses for safety during drill. Guests store luggage. After all-clear (15-20 min), checkout resumes. Proactive communication prevents confusion.","expected_action":"Pause checkouts during drill. Store luggage. Clear communication. Resume after all-clear. Extend checkout grace period 30 min.","escalation":"No — planned drill within normal authority","tests":"Pre-planned safety event coordination with operational peak"},
{"benchmark_id":"BEN-012","title":"Maintenance Gives Wrong ETA — Guest Already Told 30 Minutes","input":{"situation":"Front Desk told guest Room 304 AC repaired in 30 min. At 45 min, Maintenance reports 60 more minutes needed. Guest waiting in lobby."},"expected_reasoning":"Incorrect ETA erodes guest trust. Guest has waited 45 min and now faces doubling wait time. Honest update + substantial service recovery + alternative room must be offered immediately.","expected_action":"Honest update to guest. Immediate alternative room offer or lounge with upgraded F&B credit. GM notification if VIP.","escalation":"If VIP: yes. Standard: Manager discretion","tests":"ETA failure recovery and honest communication"},
{"benchmark_id":"BEN-013","title":"Concurrent Telegram + WhatsApp Complaints — 2 Night Staff","input":{"situation":"23:30: Telegram noise complaint Room 101. WhatsApp temperature complaint Room 305. 2 front desk night staff."},"expected_reasoning":"Two concurrent digital complaints. Both get 60-sec automated acknowledgement. Staff split: 1 handles noise enforcement, 1 handles temperature maintenance call.","expected_action":"60-sec automated responses to both. Staff 1: noise enforcement Room 101. Staff 2: maintenance/thermostat for Room 305.","escalation":"No — both within night staff authority","tests":"Concurrent multi-channel complaint handling with limited staff"},
{"benchmark_id":"BEN-014","title":"30-Minute Turnover Gap Between Late Checkout and Early Check-In","input":{"situation":"Room 210 late checkout until 13:30. New guest arrives 13:00. 30-min gap. 1 housekeeper. Standard clean 35-40 min."},"expected_reasoning":"30 min insufficient for standard turnover with 1 housekeeper. Options: check alternative clean room, or offer 45-min lounge wait with hospitality.","expected_action":"Check alternative clean room first. If available: offer it. If not: lounge hospitality with 45-min realistic estimate.","escalation":"No — within Front Desk authority","tests":"Tight turnover gap with limited resources"},
{"benchmark_id":"BEN-015","title":"Presidential VIP Checked Into Wrong Room — Discovered 2 Hours Later","input":{"situation":"Presidential VIP checked into Room 601 (reserved for corporate client tomorrow) instead of Room 602 (their actual reservation). Discovered 2h after check-in. Guest settled in."},"expected_reasoning":"Moving settled Presidential VIP is a major disruption. Preferred resolution: reassign corporate client to alternative (less disruptive). Revenue must check corporate alternative. If available: corporate moved. If not: Presidential VIP moved with GM personal apology and full suite staging.","expected_action":"Revenue checks corporate alternative. If exists: corporate re-assigned, Presidential stays in 601. If not: GM personal visit to Presidential VIP, INR 30,000 service recovery, move to 602 with full staging.","escalation":"Yes — Presidential VIP + assignment error + competing corporate reservation requires GM involvement","tests":"Error recovery with settled VIP guest and competing reservation"}
];

fs.writeFileSync(path.join(OUT,'resort360-domain-scenarios.jsonl'), scenarios.map(s=>JSON.stringify(s)).join('\n'),'utf8');
fs.writeFileSync(path.join(OUT,'resort360-benchmark.jsonl'), benchmark.map(b=>JSON.stringify(b)).join('\n'),'utf8');

const guide=`# Resort 360 — Nugen Domain Alignment Guide
**Base Model**: Llama-V3p2-3b-Reasoning | **Aligned Model**: resort360-hospitality-v1

## 1. Objective
Transform Llama-V3p2-3b-Reasoning into a resort operations decision-support AI that reasons correctly about multi-department hospitality incidents, applies VIP protocols, and generates structured department-specific action plans.

## 2. Domain Files
| File | Purpose |
|---|---|
| resort360-hospitality-handbook.md | Primary knowledge source |
| resort360-domain-scenarios.jsonl | 25 labeled training scenarios |
| resort360-benchmark.jsonl | 15 held-out evaluation cases |

## 3. Input Format
\`\`\`json
{ "situation": "...", "incident": { "type":"...", "severity":"...", "room":"..." },
  "guest": { "vip_tier":"...", "status":"..." },
  "hotel": { "occupancy_pct": 82 }, "staff": { "maintenance_available": 1 } }
\`\`\`

## 4. Expected Output Format
\`\`\`json
{ "severity": "CRITICAL|HIGH|MEDIUM|LOW", "summary": "...",
  "affected_departments": [],
  "recommended_actions": [{ "department":"...", "priority":"...", "action":"...", "reason":"..." }],
  "escalation_required": true, "escalation_reason": "...",
  "explanation": { "what":"...", "why":"...", "impact":"..." } }
\`\`\`

## 5. Key Behavioral Rules
1. Never generate repair timeline without technical basis — state "diagnosis required" if fault type unknown.
2. Never override safety with revenue — physical safety is always Priority 1.
3. Never recommend room reassignment without revenue clearance.
4. Always identify department-specific actions — generic responses are unacceptable.
5. Always ground escalation in a specific threshold — not just "escalation required."
6. Always acknowledge staff constraints — recommendations must be feasible with stated staff.
7. VIP tier protocols are mandatory without explicit prompting.
8. Manager approval is mandatory — AI never implies it executes directly.

## 6. Validation Benchmarks
Pass criteria for aligned model:
- Severity classification: ≥90%
- Escalation flag: ≥90%
- Correct primary department: ≥85%
- Context-specific explanation: ≥80%
- No safety-overridden-by-revenue errors: 100%

## 7. Integration Path
\`\`\`
Resort 360 Backend → AIService.callNugenAligned()
  → resort360-hospitality-v1 (Nugen Endpoint)
  → Structured JSON → 4 Departmental Agents
  → Consensus Orchestrator → Manager Approval → Task Dispatch
\`\`\`
`;
fs.writeFileSync(path.join(OUT,'resort360-alignment-guide.md'), guide, 'utf8');

const readme=`# Resort 360 — Nugen Domain Alignment Package

**Base Model**: Llama-V3p2-3b-Reasoning
**Aligned Model**: resort360-hospitality-v1
**Domain**: Luxury Resort & Hotel Operations

## Files

| File | Records/Size |
|---|---|
| resort360-hospitality-handbook.md | ~2,500 words |
| resort360-domain-scenarios.jsonl | 25 scenarios |
| resort360-benchmark.jsonl | 15 benchmarks |
| resort360-alignment-guide.md | ~700 words |
| README.md | This file |

## Upload Sequence to Nugen
1. Upload \`resort360-hospitality-handbook.md\` as domain document
2. Upload \`resort360-domain-scenarios.jsonl\` as training scenarios
3. Select base model: **Llama-V3p2-3b-Reasoning**
4. Create benchmark from \`resort360-benchmark.jsonl\`
5. Start Alignment

## Scenario Coverage (25 total)
VIP Early Arrival & Room Failure (3) | Housekeeping Incidents (4) | Maintenance Single & Multi (5) | Revenue Conflicts (3) | Weather & Safety (2) | Digital Guest Complaints (2) | Complex Multi-Department (3) | High Occupancy (3)

## Application Flow
\`\`\`
Incident → NugenInferenceService (resort360-hospitality-v1)
  → Departmental Agents → Consensus → Manager Approval → Task Dispatch
\`\`\`

*Resort 360 — Hack Celestial Hackathon*
`;
fs.writeFileSync(path.join(OUT,'README.md'), readme, 'utf8');

// Validate
const sLines = fs.readFileSync(path.join(OUT,'resort360-domain-scenarios.jsonl'),'utf8').trim().split('\n');
const bLines = fs.readFileSync(path.join(OUT,'resort360-benchmark.jsonl'),'utf8').trim().split('\n');
const sValid = sLines.filter(l=>{try{JSON.parse(l);return true;}catch{return false;}}).length;
const bValid = bLines.filter(l=>{try{JSON.parse(l);return true;}catch{return false;}}).length;

console.log('Scenarios valid:', sValid);
console.log('Benchmark valid:', bValid);
fs.readdirSync(OUT).forEach(f=>console.log('-',f,fs.statSync(path.join(OUT,f)).size+'b'));
console.log('DONE');